// mode changer color codes --> ["dark color", "light color"]
const navLink = ["#292929e6", "#ffffffe6"],
	asideColor = ["#ffffff", "#111419"],
	sectionLBg = ["#f3f3f3", "#343A40"],
	sectionDBg = ["#eaeaea", "#212528"],
	sectionLHead = ["#e4e4e4", "#394045"],
	sectionDHead = ["#dcdcdc", "#282D30"],
	headingColor = ["#343a39", "#ffffff"],
	silverColor = ["#505050", "#9a9da0"],
	extraLight = ["rgb(19 19 19 / 70%)", "rgba(255,255,255,0.7)"],
	boxIcon = ["#ffffff", "#343A40"],
	normalColor = ["#4a4a4a", "#ffffff"],
	normalLColor = ["#3c3c3ccc", "rgba(255, 255, 255, 0.7)"],
	messageBox = ["#ffffff", "#212528"],
	footer = ["#ffffff", "#212528"],
	lightBorder = ["rgb(0 0 0 / 10%)", "rgba(255, 255, 255, 0.1)"];

// mode helper variables
const elementsColorVariable = [
	"--nav-link",
	"--aside-color",
	"--sectionL-bg",
	"--sectionD-bg",
	"--sectionL-heading",
	"--sectionD-heading",
	"--heading-color",
	"--silver-color",
	"--extra-light",
	"--box-icon",
	"--normal-color",
	"--normal-lColor",
	"--messages-box-bg",
	"--footer-bg",
	"--light-border",
];

const elementsColor = [
	navLink,
	asideColor,
	sectionLBg,
	sectionDBg,
	sectionLHead,
	sectionDHead,
	headingColor,
	silverColor,
	extraLight,
	boxIcon,
	normalColor,
	normalLColor,
	messageBox,
	footer,
	lightBorder,
];
